import type { Metadata } from "next";
import "./globals.css";

import Header from "@/components/Header";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Bamboo Hibachi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased relative w-screen `}
      >
        <main className="px-5 md:px-12 min-h-screen ">
          <Header />
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
